import { Router } from 'express';
import { metaRouter } from './meta.js';
import { authRouter } from './auth.js';
import { usersRouter } from './users.js';
import { groupsRouter } from './groups.js';
import { sessionsRouter } from './sessions.js';
import { nasRouter } from './nas.js';
import { reportsRouter } from './reports.js';
import { adminsRouter } from './admins.js';
import { auditRouter } from './audit.js';
import { pkiRouter } from './pki.js';
import { vpnDevicesRouter } from './vpnDevices.js';
import { vpnAndroidDownloadRouter } from './vpnAndroidDownload.js';
import { vpnAlertsRouter } from './vpnAlerts.js';
import { vpnSettingsRouter } from './vpnSettings.js';

export const apiRouter = Router();

apiRouter.use('/meta', metaRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/groups', groupsRouter);
apiRouter.use('/sessions', sessionsRouter);
apiRouter.use('/nas', nasRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/admins', adminsRouter);
apiRouter.use('/audit', auditRouter);
apiRouter.use('/pki', pkiRouter);
apiRouter.use('/vpn-devices', vpnDevicesRouter);
apiRouter.use('/vpn-android', vpnAndroidDownloadRouter);
apiRouter.use('/vpn-alerts', vpnAlertsRouter);
apiRouter.use('/vpn-settings', vpnSettingsRouter);
